include current-theme.conf

shell_integration enabled

scrollback_lines 10000

# Sends the Unix control code for backward-delete-word
map ctrl+backspace send_text all \x17

# Removes the system titlebar and window buttons
hide_window_decorations yes

# Removes any remaining OS-level window borders
window_border_width 2
window_margin_width 1.5
window_padding_width 0
single_window_margin_width 0

# hide mouse during type
mouse_hide_wait -3.0

tab_bar_edge                top
tab_bar_style               custom
tab_bar_custom_style        tab_bar
active_tab_font_style       normal
inactive_tab_font_style     normal

# notification
notify_on_cmd_finish invisible 20

# Enable cursor trails. A higher number (e.g., 10 to 30) creates a longer trail.
cursor_trail 20
cursor_trail_start_threshold 0
cursor_trail_decay 0.1 0.3

allow_remote_control yes
listen_on unix:@mykitty  # See $ echo unix:@mykitty-97336
listen_on unix:/tmp/kitty

enabled_layouts splits,stack

# remove confirm on close kitty
confirm_os_window_close 0

# background_opacity 0.9
dynamic_background_opacity yes

# url open with ctrl+click
mouse_map left click ungrabbed mouse_handle_click prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click link

# <C-S-f5>, reload config kitty 
# <C-S-h>, scrollback with nvim
scrollback_pager nvim --cmd "set eventignore=FileType" +$ +"nnoremap q ZQ" +"call nvim_open_term(0, {})" +"set number relativenumber ft=scrollback" +$ -

# BEGIN_KITTY_FONTS
font_family      JetBrainsMono Nerd Font Mono
font_size        12
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# Splits, tmux way
map ctrl+\>% launch --location=vsplit --cwd=current
map ctrl+\>" launch --location=hsplit --cwd=current
map ctrl+\>x close_window
map ctrl+\>c new_tab_with_cwd
map ctrl+\>, set_tab_title
# map ctrl+\>L swap_with_window

# Disable default pane-switch bindings
map ctrl+shift+[ no_op
map ctrl+shift+] no_op
map ctrl+shift+w no_op
map ctrl+shift+enter no_op

# Config from neovim plugin knubie/vim-kitty-navigator
map ctrl+h kitten pass_keys.py left   ctrl+h "nvim"
map ctrl+j kitten pass_keys.py bottom ctrl+j "nvim"
map ctrl+k kitten pass_keys.py top    ctrl+k "nvim"
map ctrl+l kitten pass_keys.py right  ctrl+l "nvim"
map alt+h  kitten pass_keys.py resize_window narrower alt+h "nvim"
map alt+j  kitten pass_keys.py resize_window shorter alt+j "nvim"
map alt+k  kitten pass_keys.py resize_window taller alt+k "nvim"
map alt+l  kitten pass_keys.py resize_window wider alt+l "nvim"

map cmd+shift+o launch --type=overlay kesh

tab_bar_filter session:~ or session:^$
# active_tab_title_template {session_name} {title}

# startup_session $HOME/.config/kitty/sessions/test.kitty-session
# startup_session $HOME/.config/kitty/sessions/dotfiles.kitty-session

# kitty_mod f12
# map f12>1 goto_session $HOME/.config/kitty/sessions/test.kitty-session
# map f12>2 goto_session $HOME/.config/kitty/sessions/dotfiles.kitty-session
# map f12>c launch --type=overlay --hold $HOME/.config/kitty/kitty-sessionizer.fish

# map f12>o launch --type=overlay kesh
# map f12>s goto_session
# map f12>l goto_session -1

map f12>1 launch --type=background  --title "Project Selector" $HOME/.config/kitty/scripts/kitty-session-float.sh
map f12>2 save_as_session --relocatable --use-foreground-process --match=session:. .
map f12>3 close_session .

