# # https://sw.kovidgoyal.net/kitty/sessions/#managing-multi-tab-sessions-in-a-single-os-window
kitty_mode f12

shell_integration enabled

scrollback_lines 10000

# shell $HOME/.local/share/mise/installs/aqua-fish-shell-fish-shell/latest/fish

# Sends the Unix control code for backward-delete-word
map ctrl+backspace send_text all \x17

# Removes the system titlebar and window buttons
hide_window_decorations yes

# Removes any remaining OS-level window borders
window_border_width 1.5
window_margin_width 2
window_padding_width 0
single_window_margin_width 0

# hide mouse during type
mouse_hide_wait -3.0

# tab
tab_bar_style powerline
tab_powerline_style round
tab_bar_edge top
tab_activity_symbol *

# notification
notify_on_cmd_finish invisible 20

# Enable cursor trails. A higher number (e.g., 10 to 30) creates a longer trail.
cursor_trail 20

# Set the start threshold (0 means the trail is always active).
cursor_trail_start_threshold 0

# Set decay times in seconds. The first value is the fastest decay; the second is the slowest. 
# Adjust these values to control how quickly the trail fades away.
cursor_trail_decay 0.1 0.3

allow_remote_control yes
listen_on unix:@mykitty  # See $ echo unix:@mykitty-97336

# remove confirm on close kitty
confirm_os_window_close 0

# background_opacity 0.9
dynamic_background_opacity yes

# url open with ctrl+click
mouse_map left click ungrabbed mouse_handle_click prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click link

# <C-S-h>
scrollback_pager nvim --cmd "set eventignore=FileType" +$ +"nnoremap q ZQ" +"call nvim_open_term(0, {})" +"set number relativenumber ft=scrollback" +$ -


# reload config kitty <C-S-f5>

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      JetBrainsMono Nerd Font Mono
font_size        12
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


enabled_layouts splits, stack

# Splits
map ctrl+\>| launch --location=vsplit --cwd=current
map ctrl+\>_ launch --location=hsplit --cwd=current
map ctrl+\>x close_window
map ctrl+\>c new_tab_with_cwd
map ctrl+\>, set_tab_title

# Disable default pane-switch bindings
map ctrl+shift+{ no_op
map ctrl+shift+} no_op

# Config from neovim plugin knubie/vim-kitty-navigator
map ctrl+j kitten pass_keys.py bottom ctrl+j "nvim"
map ctrl+k kitten pass_keys.py top    ctrl+k "nvim"
map ctrl+h kitten pass_keys.py left   ctrl+h "nvim"
map ctrl+l kitten pass_keys.py right  ctrl+l "nvim"
map alt+h  kitten pass_keys.py resize_window narrower alt+h "nvim"
map alt+j  kitten pass_keys.py resize_window shorter alt+j "nvim"
map alt+k  kitten pass_keys.py resize_window taller alt+k "nvim"
map alt+l  kitten pass_keys.py resize_window wider alt+l "nvim"

# map ctrl+cmd+h swap_with_window

# tab_bar_filter session:~ or session:^$

map f12>b goto_session $HOME/.config/kitty/sessions/test.kitty-session
map f12>a goto_session $HOME/.config/kitty/sessions/dotfiles.kitty-session

map f12>s goto_session
map f12>l goto_session -zz1
