scrollback_lines 5000

# Sends the Unix control code for backward-delete-word
map ctrl+backspace send_text all \x17

# Removes the system titlebar and window buttons
hide_window_decorations yes

# Removes any remaining OS-level window borders
window_border_width 1.5
window_margin_width 2
window_padding_width 0
single_window_margin_width 0

# hide mouse during type
mouse_hide_wait -3.0

# tab
tab_bar_style powerline
tab_powerline_style round
tab_bar_edge top
tab_activity_symbol *

# notification
notify_on_cmd_finish invisible 20

# Enable cursor trails. A higher number (e.g., 10 to 30) creates a longer trail.
cursor_trail 20

# Set the start threshold (0 means the trail is always active).
cursor_trail_start_threshold 0

# Set decay times in seconds. The first value is the fastest decay; the second is the slowest. 
# Adjust these values to control how quickly the trail fades away.
cursor_trail_decay 0.1 0.3

allow_remote_control yes

# remove confirm on close kitty
confirm_os_window_close 0

# background_opacity 0.9
dynamic_background_opacity yes

# url open with ctrl+click
mouse_map left click ungrabbed mouse_handle_click prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click link

# reload config kitty <C-S-f5>

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      JetBrainsMono Nerd Font Mono
font_size        12
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

kitty_mode f7

# enabled_layouts splits, stack
# # Splits
# map ctrl+\>| launch --location=vsplit --cwd=current
# map ctrl+\>_ launch --location=hsplit --cwd=current
#
# # Pane zoom / close
# map ctrl+\>z toggle_layout stack
# map ctrl+\>x close_window
#
# # Tab management (tmux-style)
# map ctrl+\>c new_tab_with_cwd
# map ctrl+\>n next_tab
# map ctrl+\>p previous_tab
# map ctrl+\>w close_tab
# map ctrl+\>, set_tab_title
#
# # Go to tab by number
# map ctrl+\>1 goto_tab 1
# map ctrl+\>2 goto_tab 2
# map ctrl+\>3 goto_tab 3
# map ctrl+\>4 goto_tab 4
# map ctrl+\>5 goto_tab 5
# map ctrl+\>6 goto_tab 6
# map ctrl+\>7 goto_tab 7
# map ctrl+\>8 goto_tab 8
# map ctrl+\>9 goto_tab 9
#
# # https://sw.kovidgoyal.net/kitty/sessions/#managing-multi-tab-sessions-in-a-single-os-window
# tab_bar_filter session:~ or session:^$
#
# # map F7>b goto_session $HOME/.config/kitty/sessions/test.kitty-session
# map F7>a goto_session $HOME/.config/kitty/sessions/dotfiles.kitty-session
#
# # map ctrl+\>k launch --type=window --bias=25 --location=hsplit kitty-zoxide-sessions --ansi
#
# map F7>s goto_session
# map F7>l goto_session -1
