[tools]
bat = "latest"
bun = "latest"
chezmoi = "latest"
eza = "latest"
lazygit = "latest"
neovim = "0.11"
node = "latest"
ripgrep = "latest"
rust = "latest"
tmux = "latest"
yarn = "4.11.0"
pnpm = "latest"
btop = "latest"
fzf = "latest"
