[tools]
bat = "latest"
bun = "latest"
chezmoi = "latest"
eza = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
rust = "latest"
tmux = "latest"
yarn = "4.16"
fzf = "latest"
tree-sitter = "latest"
gh = "latest"
zoxide = "latest"
go = "1.22"
jq = "latest"
lazydocker = "latest"
opencode = "latest"
"npm:@ff-labs/fff-node" = "latest"
"npm:hunkdiff" = "0.15.3"
"npm:sort-json" = "latest"
"npm:tslib" = "latest"
lazyjournal = "latest"
tlrc = "latest"
"npm:@googleworkspace/cli" = "latest"
