return {
  {
    'sudo-tee/opencode.nvim',
    event = 'VeryLazy',
    dependencies = {
      'nvim-lua/plenary.nvim',
      {
        'MeanderingProgrammer/render-markdown.nvim',
        opts = {
          anti_conceal = { enabled = false },
          file_types = { 'markdown', 'opencode_output' },
        },
        ft = { 'markdown', 'copilot-chat', 'opencode_output' },
      },
      'saghen/blink.cmp',
      'folke/snacks.nvim',
    },
    config = function()
      require('opencode').setup {
        keymap_prefix = '<leader>o',
        preferred_picker = 'snacks',
        preferred_completion = 'blink',
        default_global_keymaps = true,
        default_mode = 'plan',
        ui = {
          enable_treesitter_markdown = true,
          position = 'right',
          input_position = 'bottom',
          window_width = 0.40,
          display_model = true,
          display_context_size = true,
          display_cost = true,
          persist_state = true,
          icons = {
            preset = 'nerdfonts',
          },
          output = {
            filetype = 'opencode_output',
          },
        },
        keymap = {
          editor = {
            ['<leader>og'] = { 'toggle' },
            ['<leader>oi'] = { 'open_input' },
            ['<leader>oI'] = { 'open_input_new_session' },
            ['<leader>oo'] = { 'open_output' },
            ['<leader>ot'] = { 'toggle_focus' },
            ['<leader>oT'] = { 'timeline' },
            ['<leader>oq'] = { 'close' },
            ['<leader>os'] = { 'select_session' },
            ['<leader>oR'] = { 'rename_session' },
            ['<leader>om'] = { 'configure_provider' },
            ['<leader>oV'] = { 'configure_variant' },
            ['<leader>oy'] = { 'add_visual_selection', mode = { 'v' } },
            ['<leader>oY'] = { 'add_visual_selection_inline', mode = { 'v' } },
            ['<leader>oz'] = { 'toggle_zoom' },
            ['<leader>ov'] = { 'paste_image' },
            ['<leader>od'] = { 'diff_open' },
            ['<leader>o]'] = { 'diff_next' },
            ['<leader>o['] = { 'diff_prev' },
            ['<leader>oc'] = { 'diff_close' },
            ['<leader>ora'] = { 'diff_revert_all_last_prompt' },
            ['<leader>ort'] = { 'diff_revert_this_last_prompt' },
            ['<leader>orA'] = { 'diff_revert_all' },
            ['<leader>orT'] = { 'diff_revert_this' },
            ['<leader>orr'] = { 'diff_restore_snapshot_file' },
            ['<leader>orR'] = { 'diff_restore_snapshot_all' },
            ['<leader>ox'] = { 'swap_position' },
            ['<leader>ott'] = { 'toggle_tool_output' },
            ['<leader>otr'] = { 'toggle_reasoning_output' },
            ['<leader>ol'] = { 'quick_chat', mode = { 'n', 'x' } },
            ['<leader>oa'] = { 'agent', { 'select' } },
            ['<leader>os'] = false,
            ['<leader>op'] = false,
            ['<leader>o/'] = false,
          },
          input_window = {
            ['<M-v>'] = { 'paste_image', mode = 'i' },
            ['<M-m>'] = { 'switch_mode' },
            ['<M-r>'] = { 'cycle_variant', mode = { 'n', 'i' } },
            ['<esc>'] = false,
          },
          output_window = {
            ['<M-r>'] = { 'cycle_variant', mode = { 'n' } },
            ['<M-m>'] = { 'switch_mode' },
            ['<esc>'] = false,
          },
        },
        completion = {
          file_sources = {
            enabled = true,
            preferred_cli_tool = 'server',
            ignore_patterns = {
              '^%.git/',
              '^%.svn/',
              '^%.hg/',
              'node_modules/',
              '%.pyc$',
              '%.o$',
              '%.obj$',
              '%.exe$',
              '%.dll$',
              '%.so$',
              '%.dylib$',
              '%.class$',
              '%.jar$',
              '%.war$',
              '%.ear$',
              'target/',
              'build/',
              'dist/',
              'out/',
              'deps/',
              '%.tmp$',
              '%.temp$',
              '%.log$',
              '%.cache$',
            },
            max_files = 10,
            max_display_length = 50,
          },
        },
        context = {
          enabled = true,
          cursor_data = {
            enabled = false,
            context_lines = 5,
          },
          diagnostics = {
            info = false,
            warning = true,
            error = true,
            only_closest = false,
          },
          current_file = {
            enabled = true,
            show_full_path = true,
          },
          files = {
            enabled = true,
            show_full_path = true,
          },
          selection = {
            enabled = true,
          },
          buffer = {
            enabled = false,
          },
          git_diff = {
            enabled = false,
          },
        },
      }
    end,
  },
}
