return {
  {
    'folke/which-key.nvim',
    event = 'VeryLazy',
    opts = {
      preset = 'helix',
      delay = 0,
      icons = {
        mappings = vim.g.have_nerd_font,
        keys = vim.g.have_nerd_font and {} or {
          Up = ' ',
          Down = ' ',
          Left = ' ',
          Right = ' ',
          C = '<C-…> ',
          M = '<M-…> ',
          D = '<D-…> ',
          S = '<S-…> ',
          CR = '<CR> ',
          Esc = '󱊷 ',
          ScrollWheelDown = '󱕐 ',
          ScrollWheelUp = '󱕑 ',
          NL = '󰌑 ',
          BS = '󰁮',
          Space = '󱁐 ',
          Tab = '󰌒 ',
          F1 = '󱊫',
          F2 = '󱊬',
          F3 = '󱊭',
          F4 = '󱊮',
          F5 = '󱊯',
          F6 = '󱊰',
          F7 = '󱊱',
          F8 = '󱊲',
          F9 = '󱊳',
          F10 = '󱊴',
          F11 = '󱊵',
          F12 = '󱊶',
        },
      },
      spec = {
        { '<leader>e', group = '[E]xplorer' },
        { '<leader>f', group = '[F]ormat' },
        { '<leader>h', group = 'Git [h]unk', mode = { 'n', 'v' } },
        { '<leader>g', group = '[G]it' },
        { '<leader>n', group = '[N]otifications' },
        { '<leader>c', group = '[C]opy abosolute/relative' },
        { '<leader>o', group = '[O]pencode' },
        { '<leader>q', group = 'Dia[Q]nostic' },
        { '<leader>s', group = '[S]earch' },
        { '<leader>r', group = '[R]eload' },
        { '<leader>t', group = '[T]oggle' },
        { '<leader>w', group = '[W]rite buffer' },
        { 'gr', group = 'LSP Actions', mode = { 'n' } },
      },
    },
  },
}
