#:schema https://docs.jj-vcs.dev/latest/config-schema.json
[user]
  name = "azrizhaziq"

[ui]
  editor = "nvim"
  diff-formatter = ":git"
  merge-editor = "meld"

[format]
  timestamp-format = "%Y-%m-%d %H:%M:%S"

[aliases]
  L = ["log", "-r", "ancestors(@)", "--no-graph"]
  l = ["log", "--no-pager"]
  s = ["status"]
  d = ["hunk diff"]

